
const mutationTypes = {
  SET_RECOMMEND: 'SET_RECOMMEND',
  SET_RECOMMENDITEM: 'SET_RECOMMENDITEM',
  SET_RANKGF: 'SET_RANKGF',

  SET_PLAYING: 'SET_PLAYING',
  SET_PLAYMODE: 'SET_PLAYMODE',
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_PLAYINDEX: 'SET_PLAYINDEX',
  SET_SHOW_BINGPLAYER:'SET_SHOW_BINGPLAYER',
  SET_SHOW_RECOMORE:'SET_SHOW_RECOMORE'
}

export default mutationTypes
